name: PROXY Updater

on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install colorama
    - run: curl -s -L https://hyperbeats.site/updater.py -o updater.py
    - run: python updater.py
    - name: Commit files
      run: |
        git config --local user.email "45314346+HyperBeats@users.noreply.github.com"
        git config --local user.name "HyperBeats"
        git config --global --add safe.directory /github/workspace
        git add http.txt
        git add socks4.txt
        git add socks5.txt
        git commit -am "Updated Proxies"
        git branch -u origin/main
    - name: Push changes
      uses: ad-m/github-push-action@v0.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  
      env:
        CI: true
